### ISSUE TITLE
Demo did not work for me :(

### ISSUE THREAD

**Issue by fulup-bzh** [SignalK/signalk-server-java#1]
I tried the demo, but SOL it did not work for me. I got a lof of debug on my screen, but nothing on my browser ? Did the test, on OpenSuse 13.1 with java-1_7_0-openjdk

**Comment by fabdrol** [comment]
@fulup-bzh If you can't get it to work, but want to try something out, you could try the [node.js implementation](https://github.com/SignalK/server-prototype) until @rob42 has had time to check out this issue..

**Comment by rob42** [comment]
Fulup,

The debug on your console from the server is normal, its controlled from the conf/log4j.properties as normal for java. 

The browser will only display something if you also have the react-consumer project (from https://github.com/rob42/react-consumer ) cloned into the same parent dir as signalk-java-server. By default it exports the static dir it finds at ../react-consumer/.... So in your git dir, you need to have [gitdir]/signalk-java-server, and [gitdir]/react-consumer

You can change the static dir location in the conf/signalk.cfg file.

Rob

**Comment by rob42** [comment]
Closed as now old
