### ISSUE TITLE
Question: read input from TCP socket

### ISSUE THREAD

**Issue by David-2** [SignalK/signalk-server-java#10]
Hello,
I have an installation of the SignalK server, it reads the input of the Demo LocalFile and I can open a UDP socket from a client to read the NMEA and SignalK outputs.

Now I would like to send NMEA messages through a TCP socket as an Input. Can I open a TCP socket to a specific port of the SignalK server and just send the NMEA messages? If yes, what is the port I should send the data? 

I also tried to edit the config file but without success:

uncomment the client lines below to start clients which will read from the host:ports
signalk.client.tcp.connect=xxx.xxx.xxx.xxx:5557

Where xxx.xxx.xxx.xxx is the IP of another machine with an installed SignalK server reading from the Demo file. In the log file I notice some warning messages that can be related to this: 
[d #0 - NettyEventExecutorGroup] NettyConsumer WARN  No payload to send as reply for exchange: Exchange[Message: [Body is null]]

Any advice and suggestions will be greatly appreciated!

**Comment by rob42** [comment]
Did you get this working? I'm sorry I should have replied. The current server uses a json config now, if you still need this pls reopen
