### ISSUE TITLE
Use Java8

### ISSUE THREAD

**Issue by jboynes** [SignalK/signalk-server-java#14]
Is it safe to use Java 8 yet or is support for older environments still needed?

**Comment by rob42** [comment]
I prefer to support 7+. 8 is needed for RPi A and B+, and generally best for ARM, but 7 is common across PC's etc. Was there a particular 8 feature you wanted to use?

**Comment by jboynes** [comment]
Oracle [stopped providing](https://java.com/en/download/faq/java_7.xml) public updates for 7 last April so  PCs etc would be better off running the newer version. Linux still has OpenJDK 7 support from RedHat but OpenJDK 8 is also readily available. The biggest reason I've seen for sticking with 7 is Android but I was not sure if that was really a factor here (perhaps more for the core library than the server?)

The question was mainly driven by support concerns for a server application, but it would be nice to use the shiny new features. [This](https://github.com/SignalK/signalk-core-java/blob/master/src/main/java/nz/co/fortytwo/signalk/model/impl/SignalKModelImpl.java#L197) had me yearning for Optional.

**Comment by rob42** [comment]
Ive switched to using java 8 for my dev. signalk-java-\* is now supporting only java 8+ :-)
For the moment lets not use java 8 features unless we really need them, makes it easy for anyone still committed to 7
