### ISSUE TITLE
api/config: add to schema, move elsewhere or add exception to testclient?

### ISSUE THREAD

**Issue by tkurki** [SignalK/signalk-server-java#18]
Java server has content at `/signalk/v1/api/` under `config` and when testclient tries to verify the json against the schema it complains.

This should be either
- added to schema
- moved elsewhere (sibling of api and rest comes to mind)
- added as an exception in the test client

Comments?

**Comment by rob42** [comment]
Its my servers config!. It should not be accessible over the api, I will adjust.

**Comment by rob42** [comment]
Done now - closing
