### ISSUE TITLE
UDP port 5554

### ISSUE THREAD

**Issue by woobagooba** [SignalK/signalk-server-java#4]
Can't get any data from this port.

Using the simulated 0183 input from file and nast to monitor ports 5554-5557...
1. TCP 5557 is streaming 0183
2. UDP 5556 streams 0183, but only after pressing the return key
3. TCP 5555 does stream the heartbeat and is further able to accept a subscription.
4. UDP 5554.  Unable to get anything from it.

**Comment by woobagooba** [comment]
typo nast -> ncat

**Comment by rob42** [comment]
The UDP implementation is Netty, using nio. So far Ive only managed to be able to recognise that a UDP client has attached after it sends some data - hence your [CR] triggers it. Any-one with experience of Netty UDP?  

Port 5554 also requires input which would normally be the subscription. I need to do some more work on it it seems. Bit short of time at present so it may not be soon.

**Comment by rob42** [comment]
Port 5554 now works after a [CR] is sent after connection. It replies with the expected heartbeat. Sending a subscription message returns the expected results.
Closing this and opening a [CR] related bug
