### ISSUE TITLE
Locale problem with decimal formats

### ISSUE THREAD

**Issue by tkurki** [SignalK/signalk-server-java#7]
Java server outputs invalid JSON numbers and throws internal errors if the locale has something else than period character as the decimal separator.

A quick fix is to explicitly set the locale of the jvm in `startpc`:

`EXT="-Djava.util.Arrays.useLegacyMergeSort=true -Duser.country=EN -Duser.language=en"`.

**Comment by rob42** [comment]
Pinned the decimal format to Locale.ENGLISH, and also disabled scientific notation on long doubles.
